esphome:
  name: eink

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eink Fallback Hotspot"
    password: "S27YLtLSq60y"

captive_portal:

# E-ink display configuration - Fixed pins for Waveshare HAT
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

# Reference local font file
font:
  - file: "opensans.ttf"
    id: font_small
    size: 25
  - file: "opensans.ttf"
    id: font_medium
    size: 60
  - file: "opensans.ttf"
    id: font_large
    size: 100
  - file: "opensans.ttf"
    id: font_tiny
    size: 15

power_supply:
  - id: epaper_power
    pin: GPIO12  # Choose an available GPIO pin
    enable_time: 500ms
    keep_on_time: 10s

display:
  - platform: waveshare_epaper
    id: my_display
    model: 7.50inV2  # 7.5 inch V2 model
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    reset_duration: 2ms  
    rotation: 0
    update_interval: 300s

    lambda: |-
      // Simple, reliable display code
      it.fill(Color::BLACK);
      
      // Draw time in larger, simpler format
      auto time = id(time_sensor).now();
      if (time.is_valid()) {
        int hour = time.hour % 12 == 0 ? 12 : time.hour % 12;
        const char *am_pm = time.hour >= 12 ? "PM" : "AM";
        
        // Format time string properly
        char time_str[16];
        sprintf(time_str, "%02d:%02d %s", hour, time.minute, am_pm);
        it.print(100, 40, id(font_large), Color::WHITE, time_str);
        
        // Format date string properly
        char date_str[16];
        sprintf(date_str, "%02d/%02d/%04d", time.month, time.day_of_month, time.year);
        it.print(100, 160, id(font_medium), Color::WHITE, date_str);
      }
      
      // Weather information title (smaller and moved down)
      it.print(100, 260, id(font_small), Color::WHITE, "Weather:");
      
      // Try to display weather condition - fixed approach
      if (id(weather_condition).has_state()) {
        // Using a different approach to display the condition
        std::string condition = id(weather_condition).state;
        if (!condition.empty()) {
          // Capitalize first letter if possible
          condition[0] = toupper(condition[0]);
          it.print(100, 330, id(font_small), Color::WHITE, condition.c_str());
        } else {
          it.print(100, 330, id(font_small), Color::WHITE, "Unknown condition");
        }
      } else {
        it.print(100, 330, id(font_small), Color::WHITE, "No condition data");
      }
      
      // Print temperature information
      if (id(weather_temperature).has_state() && id(weather_temperature_unit).has_state()) {
        char temp_str[32];
        sprintf(temp_str, "Temperature: %.1f %s", id(weather_temperature).state, id(weather_temperature_unit).state.c_str());
        it.print(100, 370, id(font_small), Color::WHITE, temp_str);
      }
      
      // Print humidity information
      if (id(weather_humidity).has_state()) {
        char humidity_str[32];
        sprintf(humidity_str, "Humidity: %.0f%%", id(weather_humidity).state);
        it.print(100, 410, id(font_small), Color::WHITE, humidity_str);
      }
      
      // Print wind information
      if (id(weather_wind_speed).has_state() && id(weather_wind_speed_unit).has_state()) {
        char wind_str[64];
        sprintf(wind_str, "Wind: %.1f %s from %.0f°", 
                id(weather_wind_speed).state, 
                id(weather_wind_speed_unit).state.c_str(),
                id(weather_wind_bearing).state);
        it.print(100, 450, id(font_small), Color::WHITE, wind_str);
      }
      
      // Draw simple rectangle - adjusted to accommodate all content
      it.rectangle(50, 0, 660, 510, Color::WHITE);

# Add sensors to display
sensor:
  - platform: uptime
    name: "E-Ink Display Uptime"
    id: uptime_sensor
    update_interval: 60s
    
  - platform: homeassistant
    id: weather_temperature
    entity_id: weather.forecast_home
    attribute: temperature
    internal: true
    
  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.forecast_home
    attribute: humidity
    internal: true
    
  - platform: homeassistant
    id: weather_wind_speed
    entity_id: weather.forecast_home
    attribute: wind_speed
    internal: true
    
  - platform: homeassistant
    id: weather_wind_bearing
    entity_id: weather.forecast_home
    attribute: wind_bearing
    internal: true
    
  - platform: homeassistant
    id: weather_pressure
    entity_id: weather.forecast_home
    attribute: pressure
    internal: true

# Add text sensors for string-based data
text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.forecast_home
    attribute: condition
    internal: true
    
  - platform: homeassistant
    id: weather_temperature_unit
    entity_id: weather.forecast_home
    attribute: temperature_unit
    internal: true
    
  - platform: homeassistant
    id: weather_wind_speed_unit
    entity_id: weather.forecast_home
    attribute: wind_speed_unit
    internal: true
    
  - platform: homeassistant
    id: weather_pressure_unit
    entity_id: weather.forecast_home
    attribute: pressure_unit
    internal: true

time:
  - platform: homeassistant
    id: time_sensor

# Add a button to force display refresh
button:
  - platform: template
    name: "Refresh E-Ink Display"
    on_press:
    - lambda: |-
        id(my_display).fill(Color::WHITE);
        id(my_display).update();
    - component.update: my_display